In [2]:
import numpy as np

### 1. 多维性

In [4]:
arr = np.array(5)  # 创建0维的ndarray数组
print(arr)
print('arr的维度:', arr.ndim)  # 查看数组的维度

5
arr的维度: 0


In [ ]:
arr = np.array([1, 2, 3])  # 创建1维的ndarray数组
print(arr)
print('arr的维度:', arr.ndim)  # 查看数组的维度

[1 2 3]
arr的维度: 1


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])  # 创建2维的ndarray数组
print(arr)
print('arr的维度:', arr.ndim)  # 查看数组的维度

[[1 2 3]
 [4 5 6]]
arr的维度: 2


### 2. 同质性

In [6]:
arr = np.array([1, 'hello'])  # 不同的数据类型会被强制转换成相同的数据类型
print(arr)  # 将 1 --> '1'

['1' 'hello']


In [ ]:
arr = np.array([1, 2.5])  # 不同的数据类型会被强制转换成相同的数据类型
print(arr)  # 将 [1.  2.5]

[1.   2.54]
