In [34]:
import numpy as np

### 1. ndarray的创建

In [ ]:
# 基础的创建方法
list1 = [4,5,6]
arr = np.array(list1, dtype= float)  # 方法/函数 指定数据类型
print(arr.ndim)  # 属性
print(arr)

1
[4. 5. 6.]


In [ ]:
# copy
arr1 = np.copy(arr)  # 元素和原始数据相同，但不是一个数组
print(arr1)
arr1[0] = 8  # 不是指向同一内存地址
print(arr1)
print(arr)

[4. 5. 6.]
[8. 5. 6.]
[4. 5. 6.]


In [ ]:
# 预定义形状
# 全0 全1 未初始化 固定值
# 1. 全0
arr = np.zeros((2,3))  # zeros方法默认是float64
print(arr)

arr = np.zeros((2,))  # 1维
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[0. 0.]


In [ ]:
# 2. 全1
arr = np.ones((2,))  
print(arr)

[1. 1.]


In [22]:
# 3. 未初始化
arr = np.empty((4,3))
print(arr)

[[1.02748684e-311 3.16202013e-322 0.00000000e+000]
 [0.00000000e+000 1.42419937e-306 1.41974977e+161]
 [1.38379699e-047 5.39943146e-066 7.86934095e-067]
 [8.24600987e-071 6.70139721e+170 3.42105584e-032]]


In [23]:
# 4. 固定值
arr = np.full((3,4),2025)
print(arr)

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [29]:
arr1 = np.zeros_like(arr) # 像arr数组一样的0数组
print(arr1)
arr1 = np.empty_like(arr)
print(arr1)
arr1 = np.ones_like(arr)
print(arr1)
arr1 = np.full_like(arr,2026)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [36]:
# 等差数列 1 2 3 4 5
arr = np.arange(2,11,2)  # start,end,step
print(arr)

[ 2  4  6  8 10]


In [ ]:
# 等间隔数列
arr = np.linspace(0,10,5) # 把数据均分成5份
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
# 练习 用arange实现
arr = np.linspace(0, 100, 5, dtype=int) # 把数据均分成5份
print(arr)
arr = np.arange(0,101,25)
print(arr)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [43]:
# 对数间隔数列
arr = np.logspace(0,4,3,base=2) 
print(arr)

[ 1.  4. 16.]


#### 特殊矩阵的构造

In [ ]:
# 单位矩阵：主对角线上的元素为1，其他为0
arr = np.eye(3, 4, dtype=int)  
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [49]:
# 对角矩阵：主对角线上是非零的元素，其他为0
arr = np.diag([5,1,2,3])
print(arr)

[[5 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


#### 随机数组的生成

In [50]:
# 生成0-1之间的随机浮点数(均匀分布)
arr = np.random.rand(2,3)
print(arr)

[[0.63377276 0.3764863  0.66127259]
 [0.91169163 0.67443106 0.28319573]]


In [51]:
# 生成指定范围之间的随机浮点数(均匀分布)
arr = np.random.uniform(3,6,(2,3))
print(arr)

[[5.25692983 4.03269478 4.35331596]
 [5.5142176  3.49424416 3.09279205]]


In [52]:
# 生成指定范围之间的随机整数
arr = np.random.randint(3,6,(2,3))
print(arr)

[[5 5 4]
 [4 5 4]]


In [ ]:
# 生成随机数量(正态分布:两边小，中间大) (-3到3之间)
arr = np.random.randn(2,3)
print(arr)

[[-0.37318736  0.82602732 -0.22246773]
 [-0.58509482 -0.30445603 -1.81234684]]


In [58]:
# 设置随机种子
np.random.seed(20)
arr = np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]
