In [3]:
import numpy as np

#### 索引与切片

In [ ]:
# 一维数组的索引与切片
arr = np.random.randint(1,100,20)
print(arr)

[87 92 49 43 77 63 70 97 26 12 87 51 86 60 14 84 67 37 45 40]
87


In [12]:
print(arr[0])
print(arr[:])
print(arr[2:5])  # 左包右不包
print(arr[(arr>20) & (arr<70)])  # 打印大于20,小于70的元素
print(arr[slice(2,15,3)])  # start,end,step

87
[87 92 49 43 77 63 70 97 26 12 87 51 86 60 14 84 67 37 45 40]
[49 43 77]
[49 43 63 26 51 60 67 37 45 40]
[49 63 26 51 14]


In [13]:
# 一维数组的索引与切片
arr = np.random.randint(1,100,(4,8))
print(arr)

[[11 16 27  5 85 25 34 47]
 [94 22 62 38 91 80 12 44]
 [18 73 10 36 49 44 55 93]
 [ 4 46 56 64 11 82  2 59]]


In [ ]:
print(arr[1,3])
print(arr[:,:])
print(arr[1,:])
print(arr[1,2:5])
print(arr[arr>50])
print(arr[2][arr[2]>50])  # 过滤行数据
print(arr[:,3] >20)  # 过滤列数据

38
[[11 16 27  5 85 25 34 47]
 [94 22 62 38 91 80 12 44]
 [18 73 10 36 49 44 55 93]
 [ 4 46 56 64 11 82  2 59]]
[94 22 62 38 91 80 12 44]
[62 38 91]
[85 94 62 91 80 73 55 93 56 64 82 59]
[73 55 93]
[[16 27  5 25 47]
 [22 62 38 80 44]
 [73 10 36 44 93]
 [46 56 64 82 59]]
[False  True  True  True]


#### ndarray的运算

In [30]:
# 算术运算
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [29]:
# 普通列表相加是拼接列表
c = [1,2,3]
d = [4,5,6]
print(c + d)

# 想实现对应位置相加 需要循环
for i in range(len(c)):
    d[i] += c[i]
print(d)

[1, 2, 3, 4, 5, 6]
[5, 7, 9]


In [ ]:
# 二维数组的运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)


In [ ]:
# 二维数组和数字的运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a + 3)
print(a * 3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### 广播机制: 1. 获取数组形状 2. 是否可以广播

In [ ]:
# 同一纬度：相同、1
a = np.array([1,2,3])  # 1*1
b = np.array([[4],[5],[6]])  # 3*1
print(a + b)
print(b - a)
'''
a: 1 2 3
   1 2 3
   1 2 3
b: 4 4 4
   5 5 5
   6 6 6
'''

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[3 2 1]
 [4 3 2]
 [5 4 3]]


In [ ]:
a = np.array([1,2,3])  # 1*3
b = np.array([[4,5]])  # 1*2
print(b - a)  # 报错

#### 矩阵的运算

In [39]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a * b)
print(a @ b)  # 矩阵的乘法

[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]
