In [1]:
import numpy as np

#### numpy中的常用函数

In [ ]:
# 1. 基本数学函数
# 计算平方根 返回浮点数
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
arr = np.array([1,25,81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [ ]:
# 计算指数 e^x
print(np.exp(1))
print(np.exp(0))

2.718281828459045


In [ ]:
# 计算自然对数 lnX
print(np.log(2.71))

0.9969486348916096


In [ ]:
# 计算正弦值、余弦值
print(np.sin(np.pi/2))
print(np.cos(np.pi))

-0.8414709848078965
-1.0


In [9]:
# 计算绝对值
arr = np.array([-1,1,-2,2])
print(np.abs(arr))

[1 1 2 2]


In [12]:
# 计算a的b次幂
arr = np.array([-1,1,-2,-3])
print(np.power(arr,3))

[ -1   1  -8 -27]


In [13]:
# 四舍五入
print(np.round([1.233,3.2,4.5,5.6]))

[1. 3. 4. 6.]


In [14]:
# 向上取整、向下取整
arr = np.array([1.6,25.1,81.7])
print(np.ceil(arr))
print(np.floor(arr))

[ 2. 26. 82.]
[ 1. 25. 81.]


In [18]:
# 检查缺失值NaN
np.isnan([1,2,0,np.nan]) # 检测是否是空缺值

array([False, False, False,  True])

In [ ]:
# 2. 统计函数
arr = np.random.randint(1,20,8)
print(arr)

[ 4 18  4 17 17  4  5  2]


In [20]:
# 求和
print(np.sum(arr))

71


In [22]:
# 计算平均值
print(np.mean(arr))

8.875


In [ ]:
# 计算中位数 
# 奇数个：排序后中间的数值
# 偶数个：排序后中间的两个数的平均值
print(np.median([1,3,2,1]))

1.5


In [27]:
# 计算标准差、方差 可以用来查看数据的离散程度
print(np.var([1,2,3]))  # 方差
print(np.std([1,2,3]))  # 标准差  
'''方差计算方法：
    1.先计算平均值 2
    2.每个数减去平均值的平方和 (1-2)^2 + (2-2)^2 + (3-2)^2
    3.除以个数 ((1-2)^2 + (2-2)^2 + (3-2)^2) / 3
   标准差的计算方法：
    在方差的基础上开根号'''
# 例：计算两台机器的误差值的标准差和方差 与平均值做对比 可以看出哪台机器更稳定
arr1 = np.array([1,2,1,2,1,1,1,2])
arr2 = np.array([1,0,3,0,0,0,4,3])
print(np.mean(arr1))
print(np.mean(arr2))
print(np.var(arr1))
print(np.var(arr2))

0.6666666666666666
0.816496580927726
1.375
1.375
0.234375
2.484375


In [29]:
# 计算最大值、最小值
print(arr)
print(np.max(arr),np.argmax(arr))  # 查看最大值索引位置
print(np.min(arr),np.argmin(arr))

[ 4 18  4 17 17  4  5  2]
18 1
2 7


In [37]:
# 分位数
print(np.median([1,2,3]))  # 查看中位数 中位数是特殊的分位数
print(np.median([1,2,3,4]))
np.random.seed(0)
arr = np.random.randint(0,100,4)
print(arr)
print(np.median(arr))
print(np.percentile(arr,25))  # 查看25%的数值

2.0
2.5
[44 47 64 67]
55.5
46.25


In [40]:
# 累积和、累积积
arr = np.array([1,2,3])
print(np.sum(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

6
[1 3 6]
[1 2 6]


In [ ]:
# 3. 比较函数
# 是否大于
print(np.greater([1,2,3,4,5,6,7],4))

[False False False False  True  True  True]


In [42]:
# 是否小于
print(np.less([1,2,3,4,5,6,7],4))

[ True  True  True False False False False]


In [ ]:
# 是否等于
print(np.equal([1,2,3,4,5,6,7],4))
print(np.equal([1,2,3],[3,3,3]))  # 数组对比形状要一样 广播机制一对一比较

[False False False  True False False False]
[False False  True]


In [48]:
# 与或非
print(np.logical_and([1,0],[1,1]))
print(np.logical_or([1,0],[1,1]))
print(np.logical_not([1,0]))


[ True False]
[ True  True]
[False  True]


In [ ]:
# 检查元素是否至少有一个元素为True
print(np.any([0,1,0]))
print(np.any([0,0,0]))

True
False


In [52]:
# 检查元素是否全部为True
print(np.all([0,1,0]))
print(np.all([1,1,1]))

False
True


In [55]:
# 自定义条件
# print(np.where(条件,条件成立表达式,条件不成立表达式))
arr = np.array([1,2,3,4,5])
print(np.where(arr>3, arr, 0))
# 例
score = np.random.randint(50,100,20)
print(score)
print(np.where(score>=60,'及格', '不及格'))

[0 0 0 4 5]
[53 89 59 69 71 86 73 56 74 74 62 51 88 89 73 96 74 67 87 75]
['不及格' '及格' '不及格' '及格' '及格' '及格' '及格' '不及格' '及格' '及格' '及格' '不及格' '及格' '及格'
 '及格' '及格' '及格' '及格' '及格' '及格']


In [56]:
# np.select(条件，返回的结果)
print(np.select([score>80,(score>=60) & (score<=80),score<60],
                ['优秀','良好','不及格'],
                default='未知'))

['不及格' '优秀' '不及格' '良好' '良好' '优秀' '良好' '不及格' '良好' '良好' '良好' '不及格' '优秀' '优秀'
 '良好' '优秀' '良好' '良好' '优秀' '良好']


In [62]:
# 4. 排序函数
np.random.seed(0)
arr = np.random.randint(1,100,20)
print(arr)
# 升序
print(np.sort(arr))  # 不改变原有数组
print(arr)
print(np.argsort(arr))  # 查看索引占位的升序
print(arr.sort())  # 返回值为None 改变原有数组
print(arr)


[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6  9 17 11 12 19]
None
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]


In [63]:
# 去重函数
print(np.unique(arr))

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


In [65]:
# 数组的拼接
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.concatenate((arr1,arr2)))

[1 2 3 4 5 6]


In [66]:
# 数组的分割
print(np.split(arr,4))

[array([10, 13, 22, 37, 40], dtype=int32), array([45, 47, 48, 59, 65], dtype=int32), array([66, 68, 68, 71, 84], dtype=int32), array([88, 88, 89, 89, 89], dtype=int32)]


In [69]:
# 调整数组的形状
print(np.reshape(arr,[4,5]))

[[10 13 22 37 40]
 [45 47 48 59 65]
 [66 68 68 71 84]
 [88 88 89 89 89]]
