In [2]:
import numpy as np

In [ ]:
'''某城市一周的最高气温为[28,30,29,31,32,30,29]
    计算平均气温，最高气温和最低气温
    气温超过30度的天数'''

In [16]:
temps = np.array([28,30,29,31,32,30,29])
print('平均气温:%.3f' %np.mean(temps))
print('最高气温:%i' %np.max(temps))
print('最低气温:%i' %np.min(temps))
print('气温超过30的天数:',len(temps[temps>30]))
print(np.cumsum(np.where(temps>30,1,0))[-1])
print(np.count_nonzero(temps>30))

平均气温:29.857
最高气温:32
最低气温:28
气温超过30的天数: 2
2
2


In [ ]:
'''学生成绩统计
    某班级5名学生数学成绩为[85,90,78,92,88]
    计算成绩的平均分、中位数和标准差
    将成绩转换成百分制(满分10)'''

In [19]:
score = np.array([85,90,78,92,88])
print('平均分：%.3f'%np.mean(score))
print('中位数: %.3f'%np.median(score))
print('标准差: %.3f'%np.var(score))
print(score/10)

平均分：86.600
中位数: 88.000
标准差: 23.840
[8.5 9.  7.8 9.2 8.8]


In [ ]:
'''矩阵运算
给定矩阵 A = [[1,2],[3,4]] 和 B = [[5,6], [7,8]]
计算 A + B 和 A * B(逐元素乘法)
计算 A和B的矩阵乘法(点积)'''

In [ ]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
print(a+b)
print(a*b)

print(a@b)
print(np.dot(a,b))

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
'''随机数据生成
    生成一个(3,4)的随机整数数组，范围[0,10)
    计算每列的最大值和每行的最小值
    将数组中所有奇数替换为-1'''

In [37]:
np.random.seed(0)
arr = np.random.randint(0,10,(3,4))
print(arr)
print(np.max(arr,axis=0))  # axis表示轴 0是列 1是行
print(np.min(arr,axis=1))
#print(np.where(arr%2==0, arr, -1))
arr[arr%2==1]=-1
print(arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[7 9 7 6]
[0 3 2]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


In [ ]:
'''数组变形
    创建一个1-12的一维数组，并转换为(3，4)的二维数组
    计算每行的和与每列的平均值
    将数组展平为一维数组'''

In [52]:
arr = np.arange(1,13,1)
print(arr)
arr1 = np.reshape(arr,(3,4))
print(arr1)
print('每行的和：',np.sum(arr1,axis=1))
print('每列的平均值',np.mean(arr1,axis=0))
print(arr.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行的和： [10 26 42]
每列的平均值 [5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
'''布尔索引
    生成一个(5,5)的随机数组，范围[0,20)
    找出数组中大于10的元素
    将所有大于10的元素替换为0
'''

In [58]:
np.random.seed(0)
arr = np.random.randint(0,20,(5,5))
print(arr)
print(arr[arr>10])
print(np.where(arr>10,0,arr))

[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
[12 15 19 18 12 14 17 13 19 16 19]
[[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


In [ ]:
'''统计函数应用
    某公司6个月的销售额(万元)为[120,135,110,125,130,140]
    计算销售额的总和、均值和方差
    找出销售额最高的月份和最低的月份'''

In [61]:
arr = np.array([120,135,110,125,130,140])
print('销售额总和：',np.sum(arr))
print('均值：',np.mean(arr))
print('方差：',np.var(arr))
print('销售额最高的月份：',np.argmax(arr)+1)
print('销售额最低的月份：',np.argmin(arr)+1)

销售额总和： 760
均值： 126.66666666666667
方差： 97.22222222222223
销售额最高的月份： 6
销售额最低的月份： 3


In [ ]:
'''数组拼接
    给定a = [1,2,3] 和 b=[4,5,6]
    将a和b水平拼接为一个新数组
    将a和b垂直拼接为一个新数组'''

In [66]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate([a,b])  # 拼接数组
print(c)
print(np.reshape(c,(2,3)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
'''唯一值与排序
    给定数组[2,1,2,3,1,4,3]
    找出数组中的唯一值并排序
    计算每个唯一值出现的次数'''

In [68]:
arr = np.array([2,1,2,3,1,4,3])
u_arr,counts = np.unique(arr,return_counts=True)
print(u_arr,counts)

[1 2 3 4] [2 2 2 1]


In [ ]:
'''综合应用
    某商店5天的销售额(万元)和成本(万元)如下：
    销售额：[20,25,22,30,28]
    成本：[15,18,16,22,20]
    计算每天的利润(销售额-成本)
    计算利润的平均值和标准差
    找出利润最高的天数'''

In [75]:
money = np.array([20,25,22,30,28])
basic = np.array([15,18,16,22,20])
lirun = money - basic
print(lirun)
print('平均值：',np.mean(lirun))
print('标准差:',np.std(lirun))
print( len(lirun[lirun==np.max(lirun)] ))


[5 7 6 8 8]
平均值： 6.8
标准差: 1.16619037896906
2
